version: "3.7"

services:
  server:
    container_name: shopify_test_server
    build:
      dockerfile: ../containers/server/Dockerfile
      context: ./server
    ports:
      - "3000:3000"
    volumes:
      - /home/shopify_test/project/tmp
      - ./server/:/home/shopify_test/project/:cached
    command: bash -c "bundle exec rails s -b 0.0.0.0"
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    container_name: shopify_test_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./containers/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - db:/var/lib/mysql

volumes:
  db:
