# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.3"

gem "rails", "~> 5.2.3"

gem "bootsnap", ">= 1.1.0", require: false
gem "config"
gem "factory_bot_rails"
gem "faker"
gem "faraday"
gem "faraday_middleware"
gem "mysql2", ">= 0.4.4", "< 0.6.0"
gem "puma", "~> 3.11"
gem "ransack"
gem "shopify_app", "~> 15.0"
gem 'turbolinks', '~> 5'

group :test do
  gem "database_cleaner"
end

group :development, :test do
  gem "awesome_print"
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "debase", "~> 0.2.3.0"
  gem "dotenv-rails"
  gem "faraday-detailed_logger"
  gem "pry"
  gem "pry-byebug"
  gem "rspec-rails", "~> 3.8"
  gem "rspec_junit_formatter"
  gem "ruby-debug-ide"
  gem "rubycritic", require: false
end

group :development do
  gem "annotate"
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "rubocop", require: false
  gem "rubocop-inflector", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem "shopify_app", "~> 15.0"
